baseurl = "/"
title = "DHSI Coding Fundamentals 2022"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"   # Chroma Style Gallery https://xyproto.github.io/splash/docs/longer/all.html
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
 repourl = "https://github.com/ComputeCanada/dhsi_2022"
 info = "Coding Fundamentals for Humanists"
 wgavatar = "/img/dhsi_logo.png"
 favicon_32 = "/img/dhsi_logo.png"
 footercontent = "Help & Info"
 dateformat = "January 2, 2006"
 hideCredits = false
 hideCopyright = false
 since = 2022

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Monday"
            weight = 1
            url = "day1"

            [[languages.en.menu.main]]
            name = "Tuesday"
            weight = 2
            url = "day2"

            [[languages.en.menu.main]]
            name = "Wednesday"
            weight = 3
            url = "day3"

            [[languages.en.menu.main]]
            name = "Thursday"
            weight = 4
            url = "day4"

	    [[languages.en.menu.main]]
	    name = "Friday"
	    weight = 5
	    url  = "day5"
